## 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [54]:
list=[10,20,30,40,50]

In [55]:
list

[10, 20, 30, 40, 50]

In [56]:
#append 
list.append(60)
list

[10, 20, 30, 40, 50, 60]

In [57]:
#extend
list.extend([70])
list

[10, 20, 30, 40, 50, 60, 70]

In [58]:
# insert
list.insert(0,80)
list

[80, 10, 20, 30, 40, 50, 60, 70]

In [59]:
## remove
list.remove(70)
list

[80, 10, 20, 30, 40, 50, 60]

In [60]:
## pop
list.pop()
list

[80, 10, 20, 30, 40, 50]

In [61]:
list.pop(2)
list

[80, 10, 30, 40, 50]

In [62]:
##clear
list.clear()
list

[]

In [68]:
list=[10,20,30,40,50]

In [69]:
## index
list.index(20)

1

In [78]:
list.count(1)
list

[10, 20, 30, 40, 50]

In [79]:
##sort
list=[50,30,20,70,10]
list.sort()
list

[10, 20, 30, 50, 70]

In [80]:
list.reverse()
list

[70, 50, 30, 20, 10]

# 2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [82]:
t1=["Sneha","Rashmi","Laxmi"]
t1

['Sneha', 'Rashmi', 'Laxmi']

In [83]:
t1[1]

'Rashmi'

In [87]:
#tuples in Python are immutable.so we cantchange the elements. if we want to cahnge wecan create new tupple.
new_tuple = (t1[0], 'Sarala', t1[2])      
new_tuple

('Sneha', 'Sarala', 'Laxmi')

# 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [93]:
x=[1,2,3,4,2,3,5,6,1,7]
set1=set(x)
print(set1)   

## set will store unique value ,duplicate values are removed

{1, 2, 3, 4, 5, 6, 7}

# 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary

In [95]:
# Create a dictionary with keys: 'name', 'age', and 'city'
person = {
    'name': 'Akshata',
    'age': 25,
    'city': 'Jamkhandi'
}

# Print the original dictionary
print("Original dictionary:")
print(person)

# Update the age
person['age'] = 28
print(" updated age:")
print(person)

# Add a new key 'email'
person['email'] = 'akshata@1233.com'

# Print the final dictionary
print("Final dictionary after adding email:")
print(person)

Original dictionary:
{'name': 'Akshata', 'age': 25, 'city': 'Jamkhandi'}
 updated age:
{'name': 'Akshata', 'age': 28, 'city': 'Jamkhandi'}
Final dictionary after adding email:
{'name': 'Akshata', 'age': 28, 'city': 'Jamkhandi', 'email': 'akshata@1233.com'}

#  5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [105]:
age=int(input("enter your age:"))
if age>=18:
        print("you are eligible for voting")
else:
        print("you are not eligible for voting")

enter your age: 13

you are not eligible for voting

# 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [106]:
marks = int(input("Enter your marks: "))
if marks >= 90:
  print("A")
elif marks >=75:
  print("B")
elif marks >= 50:
  print("C")
else:
  print("Fail")

Enter your marks:  34

Fail

# 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [120]:
num=6
if num>0:
    print("positive")
    if num%2==0:
        print("even")
    elif num==0:
        print("zero")
    else:
        print("negative")

positive
even

# Section B: Numpy

# 8.	Create:
# - A scalar using np.array(5)
# - A 1D array with values 1 to 5
# - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [3]:
import numpy as np
sclar=np.array(5)
sclar

array(5)

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
np.array([[10,20,30],[40,50,60]])

array([[10, 20, 30],
       [40, 50, 60]])

# 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [6]:
import numpy as np
np.random.randint(0,101,size=(4,4))

array([[50,  2, 90,  4],
       [57, 34, 68, 31],
       [69, 32, 14, 54],
       [30, 60, 12, 85]], dtype=int32)

# 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [9]:
import numpy as np
import pandas as pd

In [10]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
df=pd.DataFrame(array_2d,columns=['A','B','C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

# 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- # Use .info(), .describe()
- # Select 'Name' and 'City' columns
- # Drop 'City' column
- # Fill any missing values in 'Salary' column with the mean
- # Remove any duplicate rows

In [24]:
# Create a DataFrame manually
data = {
    'Name': ['Abi', 'Anita', 'Chetana', 'Laxmi', 'Manu', 'Sonu', 'Sanchi', 'Mallu', 'Nandini', 'Sneha'],
    'Age': [25, 30, 35, 40, 45, 50, 55, 60, 65, None],
    'City': ['Pune', 'Ranchi', 'Kolkatta', 'Puri', 'Mumbai', 'Delhi', 'kolkatta', 'ranchi', 'Mumbai', 'Pune'],
    'Salary': [50000, 60000, None, 80000, 90000, 100000, 110000, 120000, None, 140000]
}
df = pd.DataFrame(data)

In [25]:
# Use .info() 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     9 non-null      float64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

In [36]:
#describe()
df.describe()

             Age         Salary
count   9.000000      10.000000
mean   45.000000   93750.000000
std    13.693064   26640.612272
min    25.000000   50000.000000
25%    35.000000   82500.000000
50%    45.000000   93750.000000
75%    55.000000  107500.000000
max    65.000000  140000.000000

In [31]:
# Select 'Name' and 'City' columns
name_city = df[['Name', 'City']]
name_city

      Name      City
0      Abi      Pune
1    Anita    Ranchi
2  Chetana  Kolkatta
3    Laxmi      Puri
4     Manu    Mumbai
5     Sonu     Delhi
6   Sanchi  kolkatta
7    Mallu    ranchi
8  Nandini    Mumbai
9    Sneha      Pune

In [35]:
# Drop 'City' column
df_no_city = df.drop('City',axis=1)
df_no_city

      Name   Age    Salary
0      Abi  25.0   50000.0
1    Anita  30.0   60000.0
2  Chetana  35.0   93750.0
3    Laxmi  40.0   80000.0
4     Manu  45.0   90000.0
5     Sonu  50.0  100000.0
6   Sanchi  55.0  110000.0
7    Mallu  60.0  120000.0
8  Nandini  65.0   93750.0
9    Sneha   NaN  140000.0

In [29]:
# Fill missing values in 'Salary' with the mean
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['Salary']

In [33]:
# Remove duplicate rows
duplicates = df.drop_duplicates()
duplicates

      Name   Age      City    Salary
0      Abi  25.0      Pune   50000.0
1    Anita  30.0    Ranchi   60000.0
2  Chetana  35.0  Kolkatta   93750.0
3    Laxmi  40.0      Puri   80000.0
4     Manu  45.0    Mumbai   90000.0
5     Sonu  50.0     Delhi  100000.0
6   Sanchi  55.0  kolkatta  110000.0
7    Mallu  60.0    ranchi  120000.0
8  Nandini  65.0    Mumbai   93750.0
9    Sneha   NaN      Pune  140000.0